name: make

on: workflow_dispatch

env:
  URL_BUSYBOX: https://busybox.net/downloads/busybox-1.37.0.tar.bz2
  URL_MINIZ: https://github.com/richgel999/miniz/releases/download/2.1.0/miniz-2.1.0.zip
  URL_DIFF3: https://raw.githubusercontent.com/openbsd/src/master/usr.bin/diff3/diff3prog.c
  MAKEFLAGS: -j2

jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v12
        with:
          version: 2.0.5

      - uses: actions/checkout@v3

      - name: Build Wasm BusyBox
        run: make $MAKEFLAGS build/wasm/busybox URL_BUSYBOX=$URL_BUSYBOX URL_MINIZ=$URL_MINIZ URL_DIFF3=$URL_DIFF3
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/wasm/busybox_unstripped.*
